### ISSUE TITLE
Adding sync feature to control 2 or more exoy one

### ISSUE THREAD

**Issue by Tycorc** [Djelibeybi/hass-ExoyONE#3]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/Djelibeybi/hass-ExoyONE/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Having trouble to keep 2 or more exoy one in sync wlth each other 

### Describe the solution you'd like

Implement the sync feature like in the app, even so the implementation seems to be bugy from time. 

### Describe alternatives you've considered

Grouping 2 exoys in ha directly, doesn't play nice with the auto
Scene switching. 

### Additional context

So maybe have all exoy one In sync mode might be a solution if possible to have ha as virtual leader

**Comment by Djelibeybi** [comment]
There's nothing in the API docs I was given that explain how the sync is done: https://docs.google.com/document/d/1VhL0otGIoRLj2bSrV6HUpJIi7iIAyNo_-uo2QFCs2Mw/edit#heading=h.r3nz148a2dvp

I'll ask on Facebook. I only have one Exoy though so if we do find out, I'll rely on your testing.

**Comment by Tycorc** [comment]
I'll gladly test, if we find a way to get it to work. the sync feature feels the same as on wled, so If i had to guess, probably some udp high port broadcast. The sync option only is available in the app, not on the web frontend.

**Comment by Tycorc** [comment]
I just talked to the guys from Exoy. They said to send the same commands to both dodecahedrons via the Api. I asked about drift when using scene auto switching, because I had the issue before and the answer was:  "possible with fixed intervals." 
Would u agree that this means the implementation of sync with scene swichting could be implemented in an Ha automation and therefore we close this issue?

I had some time to play and there are several things i don't like about their implementation. For starters it is important that the synced exoy has auto scene switching disabled, otherwise it switches scenes on it's own, even so it is in "sync" mode. Scene generation doesn't sync at all, and i don't really get what it does.

Therefore using Ha might not be the worst option

**Comment by Djelibeybi** [comment]
Yeah, the sync doesn't happen between the devices, it's just the app sending the same commands to multiple devices. I sniffed for network traffic and there's nothing being sent. 

I thought about what could be done from the HA side: perhaps an additional "Random" effect that changed the effect every "timeout" seconds. It would probably have to be configured as an action and not something per-device which is how HA usually works.

Though, it's easy enough to create an action that does this already, so 🤷🏻

**Comment by Djelibeybi** [comment]
I'm going to close this for now. If you have any other issues/suggestions, please open a new issue.
